# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a2141991218e1bd3ac7b5f0d36b3be8572513a1e439850f01841f361573397b40a513ce6108e337f4a2bf547ce897e2f40057c4655d7e0d170998189ace35fb1

test:
  secret_key_base: 19bb181c3753a8c07f6bdb704710f6440ec6e2569bfd67915d29627c077543f1d8084c5223457f1cb3de448f1f07d7397978b35c8cbacd3078e22b4ba7f9ce15

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: 19bb181c3753a8c07f6bdb704710f6440ec6e2569bfd67915d29627c077543f1d8084c5223457f1cb3de448f1f07d7397978b35c8cbacd3078e22b4ba7f9ce15 #<%= ENV["SECRET_KEY_BASE"] %>
